#!/usr/bin/env bash
# Local release builder — produces signed iOS .ipa + macOS .pkg.
#
# Called by fastlane/Fastfile's `release` lane. Usage:
#   ci/local-release-check.sh v0.1.0 --sign-ios --sign-macos
#   ci/local-release-check.sh v0.1.0 --sign-ios               # iOS only
#   ci/local-release-check.sh v0.1.0 --sign-macos             # macOS only
#   ci/local-release-check.sh v0.1.0 --sign                   # both
#
# Output (created if missing):
#   build/App-<version>.ipa
#   build/App-<version>.pkg
#
# Reads .bootstrap.env (or .env.local if present) for:
#   FASTLANE_TEAM_ID  (or APPLE_TEAM_ID as a fallback name)
# Reads app/Identity.xcconfig for BUNDLE_ID, through `ruby bin/lib/xcconfig.rb`
# — the one xcconfig parser in this repository (D-57), Ruby core only.
# RELEASE_BUNDLE_ID overrides the value; IDENTITY_XCCONFIG overrides the file
# and prints a loud line saying so (red controls only — never set it for a
# release).
#
# Distribution cert + Mac Installer Distribution cert must be in the login
# Keychain. Provisioning profiles are auto-generated by `-allowProvisioningUpdates`
# during archive.
#
# Includes the macOS app-sandbox re-sign hack: Xcode's auto-managed Mac App
# Store profile strips com.apple.security.app-sandbox; TestFlight rejects
# sandbox-less .pkgs with ITMS-90296. We expand the .pkg, force-add sandbox
# entitlements, repack.

set -euo pipefail

# ── Args ──────────────────────────────────────────────────────────────────────

if [ "${1:-}" = "--help" ] || [ -z "${1:-}" ]; then
  sed -n '2,/^set -e/p' "$0" | sed 's/^# \{0,2\}//' | sed '$d'
  exit 0
fi

TAG="${1}"
SIGN_IOS=false
SIGN_MACOS=false

for arg in "${@:2}"; do
  case $arg in
    --sign-ios)   SIGN_IOS=true ;;
    --sign-macos) SIGN_MACOS=true ;;
    --sign)       SIGN_IOS=true; SIGN_MACOS=true ;;
  esac
done

# ── Setup ─────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [ -f .bootstrap.env ]; then
  # shellcheck disable=SC1091
  set -a; source .bootstrap.env; set +a
fi

TEAM_ID="${FASTLANE_TEAM_ID:-${APPLE_TEAM_ID:-}}"
if [ -z "$TEAM_ID" ] && { $SIGN_IOS || $SIGN_MACOS; }; then
  echo "FAIL: FASTLANE_TEAM_ID (or APPLE_TEAM_ID) not set; populate via .bootstrap.env or env-export before running" >&2
  exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

if command -v xcbeautify >/dev/null 2>&1; then
  XCBEAUTIFY=( xcbeautify --renderer terminal )
else
  XCBEAUTIFY=( cat )
fi

step() { printf '\n==> %s\n' "$*"; }
ok()   { printf '    ✓ %s\n' "$*"; }
warn() { printf '    ! %s\n' "$*" >&2; }
fail() { printf '    ✗ %s\n' "$*" >&2; exit 1; }


# timestamp.apple.com (Apple's RFC 3161 timestamp service used by codesign
# --timestamp and productbuild --timestamp) has known transient unavailability
# on CI runners. Wrap calls so a single blip during the weekly cron doesn't
# fail the whole release.
with_timestamp_retry() {
  local label="$1"; shift
  local out
  for attempt in 1 2 3 4 5; do
    if out=$("$@" 2>&1); then
      echo "$out"
      return 0
    fi
    if echo "$out" | grep -q "timestamp service is not available"; then
      echo "$out" >&2
      echo "    ⚠  $label: timestamp.apple.com blip (attempt $attempt/5); retrying in $((attempt * 5))s…" >&2
      sleep $((attempt * 5))
      continue
    fi
    echo "$out" >&2
    return 1
  done
  echo "    ✗ $label: timestamp.apple.com kept failing after 5 attempts" >&2
  return 1
}
# Apple Distribution cert SHA-1 resolver — shared library; SHA-pinned across consumer repos.
. "$(dirname "${BASH_SOURCE[0]}")/lib/resolve-dist-cert-sha.sh"

VERSION="${TAG#v}"
# Tag carries marketing version and (new format) build number:
#   v1.0.0+5                  → MARKETING=1.0.0, BUILD=5  (apple-shipkit v1.7+ default)
#   v0.YYYY.WW-canary-N-gen   → MARKETING=0.YYYY.WW, BUILD=$RELEASE_BUILD_NUMBER (canary)
#   v2026.19.1357             → MARKETING=2026.19.1357,   BUILD=$RELEASE_BUILD_NUMBER (legacy)
#
# Env overrides win over the tag-derived values:
#   RELEASE_MARKETING_VERSION  — canary uses this to pin a per-week
#                                marketing version on a shared bundle
#                                without editing project.yml.
#   RELEASE_BUILD_NUMBER       — CI uses this when the workflow wants
#                                deterministic numbering tied to
#                                github.run_number (canary case).
#
# Both default to 0/empty when nothing supplies them; ASC will reject
# the upload if CFBundleVersion=0 collides with an existing build.
case "$VERSION" in
  *"+"*)
    TAG_MARKETING="${VERSION%%+*}"
    TAG_BUILD="${VERSION##*+}"
    ;;
  *"-"*)
    TAG_MARKETING="${VERSION%%-*}"
    TAG_BUILD=""
    ;;
  *)
    TAG_MARKETING="$VERSION"
    TAG_BUILD=""
    ;;
esac
MARKETING_VERSION="${RELEASE_MARKETING_VERSION:-$TAG_MARKETING}"
BUILD_NUMBER="${RELEASE_BUILD_NUMBER:-${TAG_BUILD:-0}}"

# Bundle id is required when building manual-signing ExportOptions plists
# (provisioningProfiles dict maps bundle_id → profile name). Read from
# app/Identity.xcconfig's BUNDLE_ID, the one tracked identity source both
# generators resolve. project.yml carries only the `$(BUNDLE_ID)` reference,
# so grepping it yields the unresolved reference rather than a value — and an
# emptiness guard beside that grep can never fire (UL-032). Overridable via
# RELEASE_BUNDLE_ID env. An empty value or any unresolved `$(…)` reference is
# rejected here, before any archive: it would otherwise become the
# provisioningProfiles dict key and fail only after a full signed archive.
#
# The reader is `ruby bin/lib/xcconfig.rb` — the one xcconfig parser in this
# repository (D-57), Ruby core only, no bundle install. It is called rather than
# reimplemented because the line that used to live here was a `sed` capture of
# `([^[:space:]/]+)`, which stops at the first space OR slash: measured against
# the live file on 2026-09-02 it returned BUNDLE_ID correctly and truncated
# DISPLAY_NAME to `Shipkit` and COPYRIGHT to `Copyright`. It was right about the
# one value it was written for and wrong about the next two, which is what every
# hand-rolled reader of this format in this repository has been (UL-035). The
# parser reproduces Xcode's semantics against fixtures observed with
# `xcodebuild -showBuildSettings`: last assignment wins across `#include`
# boundaries, `//` opens a comment at any position, `$(VAR)` is expanded.
#
# IDENTITY_XCCONFIG exists for the red controls only and announces itself when
# set, the same discipline as bin/preflight-identity.rb's --config banner: a run
# pointed at a fixture must never be mistakable for a release run in a log. CI
# never sets it.
if [ -n "${IDENTITY_XCCONFIG+x}" ]; then
  IDENTITY_XCCONFIG_OVERRIDDEN=true
else
  IDENTITY_XCCONFIG_OVERRIDDEN=false
fi
IDENTITY_XCCONFIG="${IDENTITY_XCCONFIG:-app/Identity.xcconfig}"
if [ "$IDENTITY_XCCONFIG_OVERRIDDEN" = true ]; then
  warn "identity: reading ${IDENTITY_XCCONFIG} (IDENTITY_XCCONFIG override) — not a release configuration"
fi

if [ -n "${RELEASE_BUNDLE_ID:-}" ]; then
  BUNDLE_ID="$RELEASE_BUNDLE_ID"
else
  # The parser's exit codes are 0 value / 3 undefined-or-empty / 2 usage, and a
  # broken `#include` or an unreadable path is a NAMED error at some other
  # non-zero. Do not collapse them: 04-02 kept "your include is broken" and
  # "that key is empty" distinguishable on purpose, because being unable to tell
  # them apart is the whole reason the parser exists. `&& X=0 || X=$?` and not
  # `if !`, because `!` rewrites $? to 1 and would report every failure as 1.
  BUNDLE_ID="$(ruby bin/lib/xcconfig.rb "$IDENTITY_XCCONFIG" BUNDLE_ID)" && XCCONFIG_EXIT=0 || XCCONFIG_EXIT=$?
  case "$XCCONFIG_EXIT" in
    0) ;;
    3) fail "BUNDLE_ID is missing or empty in ${IDENTITY_XCCONFIG} — define it there (a value that is only a \`//\` comment is empty, as Xcode reads it), or set RELEASE_BUNDLE_ID to override" ;;
    *) fail "could not read BUNDLE_ID from ${IDENTITY_XCCONFIG}: ruby bin/lib/xcconfig.rb exited ${XCCONFIG_EXIT}, which is NOT its exit-3 'undefined or empty' code — a broken #include, an unreadable path, or no ruby on PATH. Its own message is above." ;;
  esac
fi
# Still here, and still after the override branch: RELEASE_BUNDLE_ID is operator
# input and can itself carry an unresolved reference — that is red control (b).
case "$BUNDLE_ID" in
  ''|*'$('*)
    fail "Could not determine BUNDLE_ID (got '${BUNDLE_ID}') — set RELEASE_BUNDLE_ID env or check BUNDLE_ID in ${IDENTITY_XCCONFIG}" ;;
esac

# ── Tag format check ──────────────────────────────────────────────────────────

step "Tag format"
if echo "$TAG" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+([-+].+)?$'; then
  ok "$TAG"
else
  fail "Tag '$TAG' does not match v[0-9]+.[0-9]+.[0-9]+(...) (e.g. v0.1.0, v0.1.0-rc1)"
fi

# ── App icon ──────────────────────────────────────────────────────────────────

# Before the archive, not after: an icon problem should cost seconds, not a full
# signed build. This template's own icon is a placeholder, so this gate lives on
# the release path rather than in local-check.sh — building with it is fine,
# shipping it is a Guideline 2.3.8 rejection.
step "App icon"
"$REPO_ROOT/ci/check-app-icon.sh" || fail "placeholder app icon — see ci/check-app-icon.sh"

# The team is passed on the xcodebuild command line below (DEVELOPMENT_TEAM=
# "$TEAM_ID" from .bootstrap.env), so the gitignored app/Local.xcconfig is not
# required here; the four identity values are.
step "App identity"
"$REPO_ROOT/ci/check-identity.sh" || fail "app/Identity.xcconfig incomplete — see ci/check-identity.sh"

# ── Regenerate xcodeproj + Generated-Info.plist ───────────────────────────────

step "xcodegen generate"
( cd app && xcodegen generate >/dev/null )
ok "App.xcodeproj regenerated"

mkdir -p "$REPO_ROOT/build"

# ─────────────────────────────────────────────────────────────────────────────
# App Store Connect API auth for xcodebuild (-authenticationKeyPath etc.)
# ─────────────────────────────────────────────────────────────────────────────
# When the three ASC_API_KEY_* env vars are set (locally via .bootstrap.env /
# secrets.env, in CI via GH Secrets), decode the .p8 to a temp file and
# thread it through every xcodebuild invocation. -allowProvisioningUpdates
# then resolves match-installed profiles via API key auth — no Apple ID
# account, no interactive login. Without these flags on a CI runner,
# xcodebuild prints "No Accounts: Add a new account in Accounts settings."
# and aborts.
#
# When the env vars aren't set (purely-local dev with profiles already
# in the login keychain), ASC_AUTH_ARGS stays empty and xcodebuild falls
# back to keychain-based account lookup as before.
ASC_AUTH_ARGS=()
if [ -n "${ASC_API_KEY_ID:-}" ] && [ -n "${ASC_API_KEY_ISSUER_ID:-}" ] && [ -n "${ASC_API_KEY_P8_BASE64:-}" ]; then
  ASC_KEY_PATH="$WORK_DIR/AuthKey_${ASC_API_KEY_ID}.p8"
  printf '%s' "$ASC_API_KEY_P8_BASE64" | base64 -d > "$ASC_KEY_PATH"
  chmod 600 "$ASC_KEY_PATH"
  ASC_AUTH_ARGS=(
    -authenticationKeyPath "$ASC_KEY_PATH"
    -authenticationKeyID "$ASC_API_KEY_ID"
    -authenticationKeyIssuerID "$ASC_API_KEY_ISSUER_ID"
  )
  ok "xcodebuild ASC API key auth enabled (key id ${ASC_API_KEY_ID})"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Manual signing overrides (CI-driven; via match's profile name env vars)
# ─────────────────────────────────────────────────────────────────────────────
# When RELEASE_IOS_PROFILE_NAME / RELEASE_MACOS_PROFILE_NAME are set
# (release lane reads them from match's `sigh_<bundle>_<type>_profile-name`
# env vars and threads them through), switch xcodebuild to MANUAL signing.
#
# Why: xcodebuild's `automatic` signing path tries Apple's "cloud signing"
# during exportArchive, which fails on CI runners with API-key-only auth:
#   error: exportArchive Cloud signing permission error
#   error: exportArchive No profiles for '...' were found
# Manual signing skips cloud signing entirely and uses the match-installed
# profile by name. Required for the iOS / macOS export steps.
#
# When the env vars are absent (legacy local dev where Xcode is logged into
# Apple ID), arrays stay empty and the existing automatic flow runs unchanged.
IOS_SIGN_ARGS=()
MACOS_SIGN_ARGS=()
PATCH_IOS_PLIST=false
PATCH_MACOS_PLIST=false
if [ -n "${RELEASE_IOS_PROFILE_NAME:-}" ]; then
  IOS_SIGN_ARGS=(
    CODE_SIGN_STYLE=Manual
    "PROVISIONING_PROFILE_SPECIFIER=$RELEASE_IOS_PROFILE_NAME"
  )
  if [ -n "${RELEASE_IOS_CERT_SHA1:-}" ]; then
    # Pin to the exact cert SHA-1 the profile binds to. Without this,
    # xcodebuild's "Apple Distribution" substring match is ambiguous when
    # the keychain has multiple Apple-valid certs of that name (cert
    # rotation, multi-team accounts, etc.) — it can pick a cert NOT bound
    # to the profile, and exportArchive fails with:
    #   "Provisioning profile X doesn't include signing certificate Y"
    # The release lane in fastlane/Fastfile extracts the cert hash from
    # DeveloperCertificates[0] of the profile sigh just minted/installed.
    IOS_SIGN_ARGS+=("CODE_SIGN_IDENTITY=$RELEASE_IOS_CERT_SHA1")
    ok "iOS manual signing → '$RELEASE_IOS_PROFILE_NAME' (cert: $RELEASE_IOS_CERT_SHA1)"
  else
    IOS_SIGN_ARGS+=("CODE_SIGN_IDENTITY=Apple Distribution")
    ok "iOS manual signing → '$RELEASE_IOS_PROFILE_NAME' (any 'Apple Distribution' cert)"
  fi
  PATCH_IOS_PLIST=true
fi
if [ -n "${RELEASE_MACOS_PROFILE_NAME:-}" ]; then
  MACOS_SIGN_ARGS=(
    CODE_SIGN_STYLE=Manual
    "PROVISIONING_PROFILE_SPECIFIER=$RELEASE_MACOS_PROFILE_NAME"
  )
  if [ -n "${RELEASE_MACOS_CERT_SHA1:-}" ]; then
    MACOS_SIGN_ARGS+=("CODE_SIGN_IDENTITY=$RELEASE_MACOS_CERT_SHA1")
    ok "macOS manual signing → '$RELEASE_MACOS_PROFILE_NAME' (cert: $RELEASE_MACOS_CERT_SHA1)"
  else
    MACOS_SIGN_ARGS+=("CODE_SIGN_IDENTITY=Apple Distribution")
    ok "macOS manual signing → '$RELEASE_MACOS_PROFILE_NAME' (any 'Apple Distribution' cert)"
  fi
  PATCH_MACOS_PLIST=true
fi

# ─────────────────────────────────────────────────────────────────────────────
# iOS archive + IPA export
# ─────────────────────────────────────────────────────────────────────────────

if $SIGN_IOS; then
  step "iOS archive (signed)"

  IOS_ARCHIVE="$WORK_DIR/App-iOS.xcarchive"
  IOS_EXPORT="$WORK_DIR/export-ios"
  EXPORT_OPTS="$WORK_DIR/ExportOptions-iOS.plist"

  cp ci/ExportOptions-iOS.plist "$EXPORT_OPTS"
  sed -i '' "s/TEAM_ID_PLACEHOLDER/$TEAM_ID/g" "$EXPORT_OPTS"

  if $PATCH_IOS_PLIST; then
    plutil -replace signingStyle -string manual "$EXPORT_OPTS"
    plutil -replace provisioningProfiles -xml \
      "<dict><key>$BUNDLE_ID</key><string>$RELEASE_IOS_PROFILE_NAME</string></dict>" \
      "$EXPORT_OPTS" 2>/dev/null || \
    plutil -insert provisioningProfiles -xml \
      "<dict><key>$BUNDLE_ID</key><string>$RELEASE_IOS_PROFILE_NAME</string></dict>" \
      "$EXPORT_OPTS"
    if [ -n "${RELEASE_IOS_CERT_SHA1:-}" ]; then
      # Pin exportArchive to the same cert the archive used. Without this,
      # exportArchive substring-matches "Apple Distribution" in the keychain
      # and can pick a cert not bound to the profile, producing:
      #   "Provisioning profile X doesn't include signing certificate Y"
      plutil -replace signingCertificate -string "$RELEASE_IOS_CERT_SHA1" "$EXPORT_OPTS" 2>/dev/null || \
      plutil -insert signingCertificate -string "$RELEASE_IOS_CERT_SHA1" "$EXPORT_OPTS"
    fi
  fi

  xcodebuild archive \
    -project app/App.xcodeproj \
    -scheme App-iOS \
    -configuration Release \
    -destination 'generic/platform=iOS' \
    -archivePath "$IOS_ARCHIVE" \
    ${ASC_AUTH_ARGS[@]+"${ASC_AUTH_ARGS[@]}"} \
    ${IOS_SIGN_ARGS[@]+"${IOS_SIGN_ARGS[@]}"} \
    -allowProvisioningUpdates \
    DEVELOPMENT_TEAM="$TEAM_ID" \
    MARKETING_VERSION="$MARKETING_VERSION" \
    CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
    2>&1 | "${XCBEAUTIFY[@]}"

  step "iOS export (App Store)"
  xcodebuild -exportArchive \
    -archivePath "$IOS_ARCHIVE" \
    -exportOptionsPlist "$EXPORT_OPTS" \
    -exportPath "$IOS_EXPORT" \
    ${ASC_AUTH_ARGS[@]+"${ASC_AUTH_ARGS[@]}"} \
    -allowProvisioningUpdates \
    2>&1 | "${XCBEAUTIFY[@]}"

  IPA_SRC=$(find "$IOS_EXPORT" -maxdepth 2 -name "*.ipa" | head -1)
  [ -z "$IPA_SRC" ] && fail "exportArchive produced no .ipa in $IOS_EXPORT"

  IPA_DEST="$REPO_ROOT/build/App-${VERSION}.ipa"
  cp "$IPA_SRC" "$IPA_DEST"
  shasum -a 256 "$IPA_DEST" > "$IPA_DEST.sha256"
  ok "$IPA_DEST"
  ok "$(cat "$IPA_DEST.sha256")"
fi

# ─────────────────────────────────────────────────────────────────────────────
# macOS archive + .pkg export (with app-sandbox re-sign)
# ─────────────────────────────────────────────────────────────────────────────

if $SIGN_MACOS; then
  step "macOS archive (signed)"

  MACOS_ARCHIVE="$WORK_DIR/App-macOS.xcarchive"
  MACOS_EXPORT="$WORK_DIR/export-macos"
  EXPORT_OPTS_MACOS="$WORK_DIR/ExportOptions-macOS-AppStore.plist"

  cp ci/ExportOptions-macOS-AppStore.plist "$EXPORT_OPTS_MACOS"
  sed -i '' "s/TEAM_ID_PLACEHOLDER/$TEAM_ID/g" "$EXPORT_OPTS_MACOS"

  if $PATCH_MACOS_PLIST; then
    plutil -replace signingStyle -string manual "$EXPORT_OPTS_MACOS"
    plutil -replace provisioningProfiles -xml \
      "<dict><key>$BUNDLE_ID</key><string>$RELEASE_MACOS_PROFILE_NAME</string></dict>" \
      "$EXPORT_OPTS_MACOS" 2>/dev/null || \
    plutil -insert provisioningProfiles -xml \
      "<dict><key>$BUNDLE_ID</key><string>$RELEASE_MACOS_PROFILE_NAME</string></dict>" \
      "$EXPORT_OPTS_MACOS"
    if [ -n "${RELEASE_MACOS_CERT_SHA1:-}" ]; then
      # Same rationale as iOS: pin the .app's signing cert by SHA-1 so
      # exportArchive doesn't substring-match into a wrong cert. The
      # installer cert (below) stays as a name-prefix because the
      # installer step is separate from the .app codesign step.
      plutil -replace signingCertificate -string "$RELEASE_MACOS_CERT_SHA1" "$EXPORT_OPTS_MACOS" 2>/dev/null || \
      plutil -insert signingCertificate -string "$RELEASE_MACOS_CERT_SHA1" "$EXPORT_OPTS_MACOS"
    fi
    # The .pkg installer wrapper is signed with a SEPARATE cert from the .app
    # inside it: "3rd Party Mac Developer Installer" (Apple's name for the
    # MAC_INSTALLER_DISTRIBUTION cert type). Match installs it readonly from
    # the certs repo. Specifying the prefix-only string lets Xcode find any
    # valid installer cert in the keychain — robust against team-id drift.
    plutil -replace installerSigningCertificate -string '3rd Party Mac Developer Installer' \
      "$EXPORT_OPTS_MACOS" 2>/dev/null || \
    plutil -insert installerSigningCertificate -string '3rd Party Mac Developer Installer' \
      "$EXPORT_OPTS_MACOS"
  fi

  xcodebuild archive \
    -project app/App.xcodeproj \
    -scheme App-macOS \
    -configuration Release \
    -destination 'generic/platform=macOS' \
    -archivePath "$MACOS_ARCHIVE" \
    ${ASC_AUTH_ARGS[@]+"${ASC_AUTH_ARGS[@]}"} \
    ${MACOS_SIGN_ARGS[@]+"${MACOS_SIGN_ARGS[@]}"} \
    -allowProvisioningUpdates \
    $($PATCH_MACOS_PLIST && echo "" || echo "CODE_SIGN_STYLE=Automatic") \
    DEVELOPMENT_TEAM="$TEAM_ID" \
    MARKETING_VERSION="$MARKETING_VERSION" \
    CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
    2>&1 | "${XCBEAUTIFY[@]}"

  step "macOS export"
  xcodebuild -exportArchive \
    -archivePath "$MACOS_ARCHIVE" \
    -exportPath "$MACOS_EXPORT" \
    -exportOptionsPlist "$EXPORT_OPTS_MACOS" \
    ${ASC_AUTH_ARGS[@]+"${ASC_AUTH_ARGS[@]}"} \
    -allowProvisioningUpdates \
    2>&1 | "${XCBEAUTIFY[@]}"

  EXPORTED_PKG=$(find "$MACOS_EXPORT" -maxdepth 2 -name "*.pkg" | head -1)
  [ -z "$EXPORTED_PKG" ] && fail "exportArchive produced no .pkg in $MACOS_EXPORT"

  # ─── app-sandbox re-sign hack ──────────────────────────────────────────────
  # Xcode's auto-managed Mac App Store profile doesn't list app-sandbox as a
  # capability, so the signed .app strips com.apple.security.app-sandbox. TestFlight
  # rejects with ITMS-90296. We expand the .pkg, force-add sandbox entitlements
  # back into the .app's signature, and repack.
  step "macOS: re-sign with app-sandbox entitlements"

  PKG_EXPANDED="$WORK_DIR/pkg-expanded"
  pkgutil --expand-full "$EXPORTED_PKG" "$PKG_EXPANDED"
  EXPANDED_APP=$(find "$PKG_EXPANDED" -maxdepth 5 -name "*.app" | head -1)
  [ -z "$EXPANDED_APP" ] && fail "pkgutil --expand-full produced no .app"

  # Pin to the cert SHA-1 from the .app's embedded provisioning profile.
  APPLE_DIST_SHA=$(resolve_dist_cert_sha_from_app "$EXPANDED_APP") \
    || fail "Could not resolve cert SHA-1 from $EXPANDED_APP/Contents/embedded.provisionprofile"
  ok "Using Apple Distribution cert: $APPLE_DIST_SHA (from embedded profile)"

  # Re-sign nested frameworks/dylibs first (codesign hashes them inside-out).
  while IFS= read -r nested; do
    codesign --force --sign "$APPLE_DIST_SHA" --timestamp "$nested" 2>/dev/null || true
  done < <(find "$EXPANDED_APP/Contents/Frameworks" \( -name "*.framework" -o -name "*.dylib" \) 2>/dev/null)

  # Extract Xcode's embedded entitlements (with team-managed identifiers) and
  # merge sandbox on top. Static entitlements would lose application-identifier /
  # team-identifier and trigger error 90886.
  #
  # PlistBuddy's `Set` does NOT accept a type keyword — `Set :key bool true`
  # silently discards the `bool` arg. Use `Set :key true` (existing keys) +
  # `Add :key bool true` (new keys).
  MERGED_ENTITLEMENTS="$WORK_DIR/merged-entitlements.plist"
  codesign -d --entitlements :"$MERGED_ENTITLEMENTS" "$EXPANDED_APP"
  _set() {
    /usr/libexec/PlistBuddy -c "Set :$1 $2" "$MERGED_ENTITLEMENTS" 2>/dev/null \
      || /usr/libexec/PlistBuddy -c "Add :$1 bool $2" "$MERGED_ENTITLEMENTS"
  }
  _set com.apple.security.app-sandbox     true
  # Add others as your app needs them. Common extras:
  #   _set com.apple.security.network.client  true
  #   _set com.apple.security.network.server  true
  #   _set com.apple.security.device.camera   true

  with_timestamp_retry "codesign macOS .app (sandbox re-sign)" \
    codesign --force --sign "$APPLE_DIST_SHA" \
    --entitlements "$MERGED_ENTITLEMENTS" \
    --timestamp \
    "$EXPANDED_APP"

  step "macOS: productbuild"
  # Prefer the installer identity belonging to THIS team. A keychain holding more
  # than one "3rd Party Mac Developer Installer" — a personal team alongside an
  # org team, or a rotated cert — previously got whichever `head -1` returned.
  # productbuild then signed the .pkg with another team's installer cert, which
  # App Store Connect rejects on upload, after a full build. This is the same
  # ambiguity the code-signing path already pins away with RELEASE_MACOS_CERT_SHA1,
  # left unhandled for the installer cert.
  #
  # RELEASE_MACOS_INSTALLER_SHA1 overrides the search entirely.
  # `|| true`: under `set -euo pipefail` a zero-match grep would abort the
  # script right here — silent exit 1 — BEFORE the explicit "cert not found"
  # fail below can report it. Swallow the no-match so execution falls through
  # to the empty-INSTALLER_CERT guard, which fails loud with a fix hint.
  INSTALLER_LINES=$(security find-identity -v -p basic 2>/dev/null \
    | grep -E "3rd Party Mac Developer Installer|Mac Installer Distribution" || true)
  if [ -n "${RELEASE_MACOS_INSTALLER_SHA1:-}" ]; then
    INSTALLER_CERT="$RELEASE_MACOS_INSTALLER_SHA1"
    ok "macOS installer identity pinned → $INSTALLER_CERT"
  else
    INSTALLER_CERT=$(printf '%s\n' "$INSTALLER_LINES" | grep -F "($TEAM_ID)" \
      | head -1 | grep -oE '"[^"]+"' | tr -d '"')
    if [ -z "$INSTALLER_CERT" ]; then
      INSTALLER_CERT=$(printf '%s\n' "$INSTALLER_LINES" \
        | head -1 | grep -oE '"[^"]+"' | tr -d '"')
      [ -n "$INSTALLER_CERT" ] && \
        warn "no installer identity for team $TEAM_ID; falling back to '$INSTALLER_CERT'"
    else
      ok "macOS installer identity → '$INSTALLER_CERT'"
    fi
  fi
  [ -z "$INSTALLER_CERT" ] && fail "Mac Installer Distribution cert not found in keychain — install one from developer.apple.com → Certificates → '+' → Mac Installer Distribution"

  PKG_DEST="$REPO_ROOT/build/App-${VERSION}.pkg"
  with_timestamp_retry "productbuild .pkg" \
    productbuild --component "$EXPANDED_APP" /Applications \
    --sign "$INSTALLER_CERT" \
    --timestamp \
    "$PKG_DEST"
  shasum -a 256 "$PKG_DEST" > "$PKG_DEST.sha256"
  ok "$PKG_DEST"
  ok "$(cat "$PKG_DEST.sha256")"
fi

echo
echo "✓ Release artifacts ready for $TAG"
$SIGN_IOS   && echo "    iOS:   build/App-${VERSION}.ipa"
$SIGN_MACOS && echo "    macOS: build/App-${VERSION}.pkg"
echo
echo "Next: fastlane release uploads via pilot, then pushes the tag."
